FROM ghcr.io/arvatoaws-labs/helm-pipeline/release:latest as helm

FROM fedora:35

VOLUME /var/lib/docker

COPY --from=helm /usr/bin/helm3 /usr/bin/helm

RUN dnf upgrade -y && dnf install -y findutils parallel awscli jq python3 python3-pip make gcc gcc-c++ automake file && dnf clean all