FROM ghcr.io/arvatoaws-labs/helm-pipeline/release:latest as helm

FROM fedora:35

COPY --from=helm /usr/bin/helm3 /usr/bin/helm

RUN dnf upgrade -y && dnf module install -y nodejs:10/default && dnf install -y findutils parallel awscli jq make gcc gcc-c++ automake file && dnf clean all