FROM ghcr.io/arvatoaws-labs/helm-pipeline/release:latest as helm

FROM fedora

COPY --from=helm /usr/bin/helm3 /usr/bin/helm

RUN dnf upgrade -y && dnf install -y awscli jq python2 python2-pip make gcc gcc-c++ automake file && dnf clean all && ln -s /usr/bin/pip2 /usr/bin/pip && ln -s /usr/bin/python2 /usr/bin/python