FROM fedora

RUN dnf upgrade -y && dnf install -y awscli jq python2 make gcc gcc-c++ automake && dnf clean all && rm -f /usr/bin/pip && ln -s /usr/bin/pip2 /usr/bin/pip && unlink /usr/bin/python && ln -s /usr/bin/python2 /usr/bin/python