FROM ghcr.io/arvatoaws-labs/fedora:43

VOLUME /var/lib/docker

RUN dnf upgrade -y && dnf install -y findutils parallel awscli jq make gcc gcc-c++ automake zip openssl-devel musl-gcc musl-devel musl-clang musl-libc musl-libc-static file libcurl-devel nodejs npm lld clang && dnf clean all
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN . "$HOME/.cargo/env"
RUN echo "\nsource \"$HOME/.cargo/env\"\n" >> "$HOME/.bashrc"
RUN curl -fsSL https://cargo-lambda.info/install.sh | sh
RUN npm install -g aws-cdk