name: nodejs16

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.8.0
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: jenkins-arvato
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          file: ./Dockerfile.nodejs16
          tags: ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs16:latest
          cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs16:latest
          cache-to: type=inline