name: nodejs22

on:
  push:
    branches:
    - main
    - master
  schedule:
  - cron: '30 12 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.6.0
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.10.0
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
        # username: jenkins-arvato
        # password: ${{ secrets.CR_PAT }}
    - name: Build and Push
      uses: docker/build-push-action@v6.17.0
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        pull: true
        file: ./Dockerfile.nodejs22
        tags: ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs22:latest
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs22:latest
        cache-to: type=inline